### PR TITLE
Version 5

### PR DESCRIPTION
**Pull request by thompsnm**
I still have work left to:

- [x] update the docs
- [x] split out the giant step defs spec file
- [x] bring more uniformity to the step def names
- [x] wait for elements before allowing step defs to interact with them

The change set is already getting quite large so I decided to open up an initial PR if anyone has feedback.

### CODE REVIEW

**Comment by wyvern8** [comment]
Looking good - I'm happy to do some testing when things have settled down.  Btw, one thing I found recently is that we needed waits using expected conditions in a number of the general stepdefs before they interact with elements.  On slower selenium nodes/browsers with complex dom interactions it intermittently fails otherwise.  Eg. Wait for clickable before sending keys to input.  It is probably a good idea to start an 'opensauce' free account with saucelabs for crossbrowser testing via travis. Also, I was under the impression cucumber 2 still supports regex as well as the new pattern matching?  Just trying to plan our upgrade path.

**Comment by thompsnm** [comment]
Awesome, thanks @wyvern8 ! I agree with you on waiting to interact with elements, and I think now is a good time to make that change since I'm so deep in the code already. My hope is to be able to close issues #28 and #9 with this PR to finally clear out some of the old backlog.

I'm not sure if I'll have time to implement opensauce on this go around, but I'd definitely be open to pull requests to use it once CukeFarm v5 is settled.

You are correct that cucumber 2 still supports regex in addition to their new pattern matching. As far as CukeFarm goes, my plan is to support either syntax as well, but provide some cool new features if you do choose to go with the new pattern matching. Namely, I've used the new [`addTransform` function](https://github.com/cucumber/cucumber-js/blob/e8a785ae5eb9d401c37a8a1c9d8b653b3ec1cea9/docs/support_files/api_reference.md#addtransformcapturegroupregexps-typename-transformer) to [provide all functions in the Tranform object as Cucumber 2 transforms](https://github.com/thompsnm/cukefarm/blob/096ca4116fbab06b145e648d13776fe320e1ced2/lib/support/Transform.js#L10). That way, if you want to write a step definition that matches the following (where "Custom Element" is an element name):

    I interact with the "Custom Element"

you can write it as:

    When('I interact with the "{elementName}"', function(name) {
      return this.currentPage[name].interact();
    };

That way Cucumber handles transforming the element name for you. That said, an instance of the Transform object will [still be provided by the World](https://github.com/thompsnm/cukefarm/blob/096ca4116fbab06b145e648d13776fe320e1ced2/lib/support/World.js#L15), so if you need to use regex you can still write your step def the old way:

    When(/^I interact with the "([^"]*)"$/, function(name) {
      var formattedName = this.transform.stringToVariableName(name);
      return this.currentPage[formattedName].interact();
    };

As for my own experience upgrading to Cucumber 2, the biggest change I _had_ to make was to [define step definitions using the `defineSupportCode` function](https://github.com/cucumber/cucumber-js/blob/f40b4056964a3caa467a45c3f812c90943399891/CHANGELOG.md#breaking-changes-1). That was a pretty simple refactor though. We'll see if they make any more breaking changes before finally publishing a v2.0.0 release.

**Comment by thompsnm** [comment]
I believe all necessary work for the PR is completed. All unit tests are passing and the tests in the [cukefarm-template project](https://github.com/thompsnm/cukefarm-template) are also passing. That project only uses step definitions provided by CukeFarm, and you can view [this diff](https://github.com/thompsnm/cukefarm-template/compare/c791303117510d86a997e72f1d9bd4335345fb40...b2ffbfcca109bef270eb0c841e8baff075391758) to see the refactor necessary to work with the new version of CukeFarm. If no concerns are raised in the next week or so I'll merge this and publish a new version of CukeFarm.

**Comment by wyvern8** [comment]
Great work!  And thanks for the info on the transforms.  I'll do my best to make some time to do some review/testing in the next week.

**Comment by thompsnm** [comment]
This change set has been published as `5.0.0-rc.1`, and is intended for use with Protractor `^5.0.0` and Cucumber `2.0.0-rc.7`. A full version of CukeFarm will be published once a full version of Cucumber is published as it looks like new release candidates from the latter [may already be causing issues for this change set](https://github.com/cucumber/cucumber-js/blob/2854439d070503895fc5b3560b1d639e2fab956d/CHANGELOG.md#deprecations).

**Pull request merged**
